### mape

In [4]:
import numpy as np

In [5]:

def mean_absolute_percentage_error(y_true, y_pred): 
    return np.mean(np.abs((y_true - y_pred) / y_true)) * 100


In [6]:
true = np.arange(1, 10001)
true

array([    1,     2,     3, ...,  9998,  9999, 10000])

In [44]:
pred = np.repeat(1, 10000)
pred

array([1, 1, 1, ..., 1, 1, 1])

In [45]:
mean_absolute_percentage_error(true, pred)

99.90212393963955

In [37]:
mean_absolute_percentage_error(true, pred)

98.51132891879628

In [32]:
from scipy.optimize import fmin_bfgs

In [35]:
f = lambda x: mean_absolute_percentage_error(true, np.repeat(x, 10000))

fmin_bfgs(f, 100, epsilon=1e-6)

         Current function value: 98.511329
         Iterations: 7
         Function evaluations: 324
         Gradient evaluations: 104


array([74.99999966])

### heads

In [14]:
import math

In [15]:
def nCr(n,r):
    f = math.factorial
    return f(n) / f(r) / f(n-r)

In [53]:
k=0

for i in range(8,11):
    k+=nCr(10,i)
    
k=k/(2**10)

k

0.0546875

In [52]:
k=0

for i in range(53,101):
    k+=nCr(100,i)
    
k=k/(2**100)

k

0.3086497067946261

### fbt

In [1]:
class TreeNode:
    def __init__(self, x):
        self.val = x
        self.left = None
        self.right = None

def allPossibleFBT(N):
    if N % 2 == 0: return []
    if N == 1: return [TreeNode(0)]
    ans = []
    for i in range(1, N, 2):
        for l in allPossibleFBT(i):
            for r in allPossibleFBT(N - i - 1):
                root = TreeNode(0)
                root.left = l
                root.right = r
                ans.append(root.val)
    return ans
    
 

In [10]:
for i in range(1,28):
    print(len(allPossibleFBT(i)))

1
0
1
0
2
0
5
0
14
0
42
0
132
0
429
0
1430
0
4862
0
16796
0
58786
0
208012
0
742900


In [25]:
nCr(100,50)/51/1

1.9782616577561607e+27

In [167]:
l,u=1,10000
c=0
for i in range(l,u + 1):
    if  i> 1:
        for j in range(2,i):
            if (i%j) == 0:
                break
        else:
            c+=1
print(c)

1229


In [163]:
def approach3(givenNumber):  
    
    # Initialize a list
    primes = 0
    for possiblePrime in range(2, givenNumber + 1):
        # Assume number is prime until shown it is not. 
        isPrime = True
        for num in range(2, int(possiblePrime ** 0.5) + 1):
            if possiblePrime % num == 0:
                isPrime = False
                break
        if isPrime:
            primes+=1
    
    return(primes)

In [166]:
approach3(10000)

1229

In [ ]:
0.05761455